apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: restaurant
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.spec.ports }}

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: restaurant
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
