# Default values for mongodb-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mongo

spec:
  ports: 27017

service:
  type: ClusterIP
  port: 27017
  targetPort: 27017

