apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: restaurant
  labels:
    app: mongodb
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: {{ .Values.spec.ports }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: restaurant
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
